# Generated by Django 5.0.6 on 2024-06-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "master",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(blank=True, max_length=100, null=True)),
                ("Username", models.CharField(blank=True, max_length=100, null=True)),
                ("About", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "male"), ("f", "female")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("BirthDate", models.DateField(default="2000-01-01")),
                ("Mobile", models.CharField(blank=True, max_length=10, null=True)),
                ("City", models.CharField(blank=True, max_length=50, null=True)),
                ("State", models.CharField(blank=True, max_length=50, null=True)),
                ("Country", models.CharField(blank=True, max_length=50, null=True)),
                ("Pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("Address", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.master",
                    ),
                ),
            ],
            options={
                "db_table": "userprofile",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                (
                    "Level",
                    models.CharField(
                        choices=[
                            ("40", "beginner"),
                            ("65", "intermediate"),
                            ("100", "advance"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "skill",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProjectName", models.CharField(max_length=255)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("IsContinue", models.BooleanField(default=False)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("JobTitle", models.CharField(max_length=100)),
                ("Company", models.CharField(max_length=100)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("IsContinue", models.BooleanField(default=False)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "experience",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Course", models.CharField(max_length=255)),
                ("Standard", models.CharField(max_length=255)),
                ("BoardUniversity", models.CharField(max_length=255)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("IsContinue", models.BooleanField(default=False)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "education",
            },
        ),
    ]
