# Generated by Django 5.0.6 on 2024-07-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="About",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Address",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="City",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Country",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="FullName",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "male"), ("f", "female")],
                default="",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Mobile",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Pincode",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="State",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Username",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
