# Generated by Django 5.0.6 on 2024-07-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resumeApp",
            "0002_alter_userprofile_about_alter_userprofile_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Username",
            field=models.CharField(blank=True, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
