# Generated by Django 5.0.6 on 2024-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0003_alter_userprofile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Company",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
